// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { AddonArgs } from "./addon";
export type Addon = import("./addon").Addon;
export const Addon: typeof import("./addon").Addon = null as any;
utilities.lazyLoad(exports, ["Addon"], () => require("./addon"));

export { AddonListArgs } from "./addonList";
export type AddonList = import("./addonList").AddonList;
export const AddonList: typeof import("./addonList").AddonList = null as any;
utilities.lazyLoad(exports, ["AddonList"], () => require("./addonList"));

export { AddonPatchArgs } from "./addonPatch";
export type AddonPatch = import("./addonPatch").AddonPatch;
export const AddonPatch: typeof import("./addonPatch").AddonPatch = null as any;
utilities.lazyLoad(exports, ["AddonPatch"], () => require("./addonPatch"));

export { KeyPairArgs } from "./keyPair";
export type KeyPair = import("./keyPair").KeyPair;
export const KeyPair: typeof import("./keyPair").KeyPair = null as any;
utilities.lazyLoad(exports, ["KeyPair"], () => require("./keyPair"));

export { KeyPairListArgs } from "./keyPairList";
export type KeyPairList = import("./keyPairList").KeyPairList;
export const KeyPairList: typeof import("./keyPairList").KeyPairList = null as any;
utilities.lazyLoad(exports, ["KeyPairList"], () => require("./keyPairList"));

export { KeyPairPatchArgs } from "./keyPairPatch";
export type KeyPairPatch = import("./keyPairPatch").KeyPairPatch;
export const KeyPairPatch: typeof import("./keyPairPatch").KeyPairPatch = null as any;
utilities.lazyLoad(exports, ["KeyPairPatch"], () => require("./keyPairPatch"));

export { SettingArgs } from "./setting";
export type Setting = import("./setting").Setting;
export const Setting: typeof import("./setting").Setting = null as any;
utilities.lazyLoad(exports, ["Setting"], () => require("./setting"));

export { SettingListArgs } from "./settingList";
export type SettingList = import("./settingList").SettingList;
export const SettingList: typeof import("./settingList").SettingList = null as any;
utilities.lazyLoad(exports, ["SettingList"], () => require("./settingList"));

export { SettingPatchArgs } from "./settingPatch";
export type SettingPatch = import("./settingPatch").SettingPatch;
export const SettingPatch: typeof import("./settingPatch").SettingPatch = null as any;
utilities.lazyLoad(exports, ["SettingPatch"], () => require("./settingPatch"));

export { VirtualMachineImageArgs } from "./virtualMachineImage";
export type VirtualMachineImage = import("./virtualMachineImage").VirtualMachineImage;
export const VirtualMachineImage: typeof import("./virtualMachineImage").VirtualMachineImage = null as any;
utilities.lazyLoad(exports, ["VirtualMachineImage"], () => require("./virtualMachineImage"));

export { VirtualMachineImageListArgs } from "./virtualMachineImageList";
export type VirtualMachineImageList = import("./virtualMachineImageList").VirtualMachineImageList;
export const VirtualMachineImageList: typeof import("./virtualMachineImageList").VirtualMachineImageList = null as any;
utilities.lazyLoad(exports, ["VirtualMachineImageList"], () => require("./virtualMachineImageList"));

export { VirtualMachineImagePatchArgs } from "./virtualMachineImagePatch";
export type VirtualMachineImagePatch = import("./virtualMachineImagePatch").VirtualMachineImagePatch;
export const VirtualMachineImagePatch: typeof import("./virtualMachineImagePatch").VirtualMachineImagePatch = null as any;
utilities.lazyLoad(exports, ["VirtualMachineImagePatch"], () => require("./virtualMachineImagePatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:harvesterhci.io/v1beta1:Addon":
                return new Addon(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:AddonList":
                return new AddonList(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:AddonPatch":
                return new AddonPatch(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:KeyPair":
                return new KeyPair(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:KeyPairList":
                return new KeyPairList(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:KeyPairPatch":
                return new KeyPairPatch(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:Setting":
                return new Setting(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:SettingList":
                return new SettingList(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:SettingPatch":
                return new SettingPatch(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:VirtualMachineImage":
                return new VirtualMachineImage(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:VirtualMachineImageList":
                return new VirtualMachineImageList(name, <any>undefined, { urn })
            case "kubernetes:harvesterhci.io/v1beta1:VirtualMachineImagePatch":
                return new VirtualMachineImagePatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "harvesterhci.io/v1beta1", _module)
