export const RANCHER_VERSION = "v2.12.2";
export const HARVESTER_UIPLUGIN_VERSION = "1.5.2";
export const VIRTUAL_CLUSTERS_UIPLUGIN_VERSION = "0.1.3";
export const CERT_MANAGER_VERSION = "v1.18.1";
export const INGRESS_NGINX_VERSION = "4.13.3";