export const RANCHER_VERSION = "v2.14.1";
export const HARVESTER_UIPLUGIN_VERSION = "1.8.0";
export const VIRTUAL_CLUSTERS_UIPLUGIN_VERSION = "1.0.2";
export const KUBEWARDEN_UIPLUGIN_VERSION = "4.1.1";
export const SBOMSCANNER_UIPLUGIN_VERSION = "0.7.2";
export const AI_UIPLUGIN_VERSION = "1.0.0";
// helm show all oci://registry.suse.com/rancher/charts/rancher-ai-agent
export const AI_AGENT_VERSION = "108.0.1+up1.0.1";
export const CERT_MANAGER_VERSION = "v1.20.2";
export const TRAEFIK_VERSION = "39.0.8";
export const K3S_VERSION = "v1.35.4+k3s1";
export const RKE2_VERSION = "v1.35.4+rke2r3";
export const AUTHENTIK_VERSION = "2025.10.0";