apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: application-collection
spec:
  clientSecret:
    name: {{ .Values.secret.name }}
    namespace: {{ .Values.secret.namespace }}
  insecurePlainHttp: false
  url: {{ .Values.appcoRegistry }}
