// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { IPPoolArgs } from "./ippool";
export type IPPool = import("./ippool").IPPool;
export const IPPool: typeof import("./ippool").IPPool = null as any;
utilities.lazyLoad(exports, ["IPPool"], () => require("./ippool"));

export { IPPoolListArgs } from "./ippoolList";
export type IPPoolList = import("./ippoolList").IPPoolList;
export const IPPoolList: typeof import("./ippoolList").IPPoolList = null as any;
utilities.lazyLoad(exports, ["IPPoolList"], () => require("./ippoolList"));

export { IPPoolPatchArgs } from "./ippoolPatch";
export type IPPoolPatch = import("./ippoolPatch").IPPoolPatch;
export const IPPoolPatch: typeof import("./ippoolPatch").IPPoolPatch = null as any;
utilities.lazyLoad(exports, ["IPPoolPatch"], () => require("./ippoolPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:loadbalancer.harvesterhci.io/v1beta1:IPPool":
                return new IPPool(name, <any>undefined, { urn })
            case "kubernetes:loadbalancer.harvesterhci.io/v1beta1:IPPoolList":
                return new IPPoolList(name, <any>undefined, { urn })
            case "kubernetes:loadbalancer.harvesterhci.io/v1beta1:IPPoolPatch":
                return new IPPoolPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "loadbalancer.harvesterhci.io/v1beta1", _module)
