// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

/**
 * HarvesterConfig represents the desired configuration of each machine provisioned within a machine pool associated with a provisioning.cattle.io cluster.
 */
export class HarvesterConfig extends pulumi.CustomResource {
    /**
     * Get an existing HarvesterConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): HarvesterConfig {
        return new HarvesterConfig(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:rke-machine-config.cattle.io/v1:HarvesterConfig';

    /**
     * Returns true if the given object is an instance of HarvesterConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is HarvesterConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === HarvesterConfig.__pulumiType;
    }

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    declare public readonly apiVersion: pulumi.Output<"rke-machine-config.cattle.io/v1">;
    /**
     * just keep it empty, this value will be filled by rancher-machine
     */
    declare public readonly cloudConfig: pulumi.Output<string>;
    /**
     * harvester cluster id
     */
    declare public readonly clusterId: pulumi.Output<string>;
    /**
     * harvester cluster name
     */
    declare public readonly clusterName: pulumi.Output<string>;
    /**
     * harvester cluster type
     */
    declare public readonly clusterType: pulumi.Output<string>;
    /**
     * number of CPUs for machine
     */
    declare public readonly cpuCount: pulumi.Output<string>;
    /**
     * enable vm cpu pinning, please ensure the harvester cluster has cpu manager enabled in at least one node
     */
    declare public readonly cpuPinning: pulumi.Output<boolean>;
    /**
     * bus of disk for machine
     */
    declare public readonly diskBus: pulumi.Output<string>;
    /**
     * harvester disk info
     */
    declare public readonly diskInfo: pulumi.Output<string>;
    /**
     * size of disk for machine (in GiB)
     */
    declare public readonly diskSize: pulumi.Output<string>;
    /**
     * enable vm efi
     */
    declare public readonly enableEfi: pulumi.Output<boolean>;
    /**
     * enable vm secure boot, only works when enable efi
     */
    declare public readonly enableSecureBoot: pulumi.Output<boolean>;
    /**
     * enable vm TPM
     */
    declare public readonly enableTpm: pulumi.Output<boolean>;
    /**
     * harvester image name
     */
    declare public readonly imageName: pulumi.Output<string>;
    /**
     * enable vm isolatated emulator thread
     */
    declare public readonly isolateEmulatorThread: pulumi.Output<boolean>;
    /**
     * harvester key pair name
     */
    declare public readonly keyPairName: pulumi.Output<string>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    declare public readonly kind: pulumi.Output<"HarvesterConfig">;
    /**
     * contents of kubeconfig file for harvester cluster, base64 is supported
     */
    declare public readonly kubeconfigContent: pulumi.Output<string>;
    /**
     * size of memory for machine (in GiB)
     */
    declare public readonly memorySize: pulumi.Output<string>;
    /**
     * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    declare public readonly metadata: pulumi.Output<outputs.meta.v1.ObjectMeta>;
    /**
     * networkData content of cloud-init for machine, base64 is supported
     */
    declare public readonly networkData: pulumi.Output<string>;
    /**
     * harvester network info
     */
    declare public readonly networkInfo: pulumi.Output<string>;
    /**
     * harvester network model
     */
    declare public readonly networkModel: pulumi.Output<string>;
    /**
     * harvester network name
     */
    declare public readonly networkName: pulumi.Output<string>;
    /**
     * harvester network type
     */
    declare public readonly networkType: pulumi.Output<string>;
    /**
     * size of reserved memory for machine (in MiB, integer value)
     */
    declare public readonly reservedMemorySize: pulumi.Output<string>;
    /**
     * SSH password
     */
    declare public readonly sshPassword: pulumi.Output<string>;
    /**
     * SSH port
     */
    declare public readonly sshPort: pulumi.Output<string>;
    /**
     * SSH private key path 
     */
    declare public readonly sshPrivateKeyPath: pulumi.Output<string>;
    /**
     * SSH username
     */
    declare public readonly sshUser: pulumi.Output<string>;
    /**
     * userData content of cloud-init for machine, base64 is supported
     */
    declare public readonly userData: pulumi.Output<string>;
    /**
     * harvester-vgpu-info
     */
    declare public readonly vgpuInfo: pulumi.Output<string>;
    /**
     * harvester vm affinity, base64 is supported
     */
    declare public readonly vmAffinity: pulumi.Output<string>;
    /**
     * harvester vm namespace
     */
    declare public readonly vmNamespace: pulumi.Output<string>;

    /**
     * Create a HarvesterConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: HarvesterConfigArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "rke-machine-config.cattle.io/v1";
            resourceInputs["cloudConfig"] = args?.cloudConfig;
            resourceInputs["clusterId"] = args?.clusterId;
            resourceInputs["clusterName"] = args?.clusterName;
            resourceInputs["clusterType"] = args?.clusterType;
            resourceInputs["cpuCount"] = args?.cpuCount;
            resourceInputs["cpuPinning"] = args?.cpuPinning;
            resourceInputs["diskBus"] = args?.diskBus;
            resourceInputs["diskInfo"] = args?.diskInfo;
            resourceInputs["diskSize"] = args?.diskSize;
            resourceInputs["enableEfi"] = args?.enableEfi;
            resourceInputs["enableSecureBoot"] = args?.enableSecureBoot;
            resourceInputs["enableTpm"] = args?.enableTpm;
            resourceInputs["imageName"] = args?.imageName;
            resourceInputs["isolateEmulatorThread"] = args?.isolateEmulatorThread;
            resourceInputs["keyPairName"] = args?.keyPairName;
            resourceInputs["kind"] = "HarvesterConfig";
            resourceInputs["kubeconfigContent"] = args?.kubeconfigContent;
            resourceInputs["memorySize"] = args?.memorySize;
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["networkData"] = args?.networkData;
            resourceInputs["networkInfo"] = args?.networkInfo;
            resourceInputs["networkModel"] = args?.networkModel;
            resourceInputs["networkName"] = args?.networkName;
            resourceInputs["networkType"] = args?.networkType;
            resourceInputs["reservedMemorySize"] = args?.reservedMemorySize;
            resourceInputs["sshPassword"] = args?.sshPassword;
            resourceInputs["sshPort"] = args?.sshPort;
            resourceInputs["sshPrivateKeyPath"] = args?.sshPrivateKeyPath;
            resourceInputs["sshUser"] = args?.sshUser;
            resourceInputs["userData"] = args?.userData;
            resourceInputs["vgpuInfo"] = args?.vgpuInfo;
            resourceInputs["vmAffinity"] = args?.vmAffinity;
            resourceInputs["vmNamespace"] = args?.vmNamespace;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["cloudConfig"] = undefined /*out*/;
            resourceInputs["clusterId"] = undefined /*out*/;
            resourceInputs["clusterName"] = undefined /*out*/;
            resourceInputs["clusterType"] = undefined /*out*/;
            resourceInputs["cpuCount"] = undefined /*out*/;
            resourceInputs["cpuPinning"] = undefined /*out*/;
            resourceInputs["diskBus"] = undefined /*out*/;
            resourceInputs["diskInfo"] = undefined /*out*/;
            resourceInputs["diskSize"] = undefined /*out*/;
            resourceInputs["enableEfi"] = undefined /*out*/;
            resourceInputs["enableSecureBoot"] = undefined /*out*/;
            resourceInputs["enableTpm"] = undefined /*out*/;
            resourceInputs["imageName"] = undefined /*out*/;
            resourceInputs["isolateEmulatorThread"] = undefined /*out*/;
            resourceInputs["keyPairName"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["kubeconfigContent"] = undefined /*out*/;
            resourceInputs["memorySize"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["networkData"] = undefined /*out*/;
            resourceInputs["networkInfo"] = undefined /*out*/;
            resourceInputs["networkModel"] = undefined /*out*/;
            resourceInputs["networkName"] = undefined /*out*/;
            resourceInputs["networkType"] = undefined /*out*/;
            resourceInputs["reservedMemorySize"] = undefined /*out*/;
            resourceInputs["sshPassword"] = undefined /*out*/;
            resourceInputs["sshPort"] = undefined /*out*/;
            resourceInputs["sshPrivateKeyPath"] = undefined /*out*/;
            resourceInputs["sshUser"] = undefined /*out*/;
            resourceInputs["userData"] = undefined /*out*/;
            resourceInputs["vgpuInfo"] = undefined /*out*/;
            resourceInputs["vmAffinity"] = undefined /*out*/;
            resourceInputs["vmNamespace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(HarvesterConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a HarvesterConfig resource.
 */
export interface HarvesterConfigArgs {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    apiVersion?: pulumi.Input<"rke-machine-config.cattle.io/v1">;
    /**
     * just keep it empty, this value will be filled by rancher-machine
     */
    cloudConfig?: pulumi.Input<string>;
    /**
     * harvester cluster id
     */
    clusterId?: pulumi.Input<string>;
    /**
     * harvester cluster name
     */
    clusterName?: pulumi.Input<string>;
    /**
     * harvester cluster type
     */
    clusterType?: pulumi.Input<string>;
    /**
     * number of CPUs for machine
     */
    cpuCount?: pulumi.Input<string>;
    /**
     * enable vm cpu pinning, please ensure the harvester cluster has cpu manager enabled in at least one node
     */
    cpuPinning?: pulumi.Input<boolean>;
    /**
     * bus of disk for machine
     */
    diskBus?: pulumi.Input<string>;
    /**
     * harvester disk info
     */
    diskInfo?: pulumi.Input<string>;
    /**
     * size of disk for machine (in GiB)
     */
    diskSize?: pulumi.Input<string>;
    /**
     * enable vm efi
     */
    enableEfi?: pulumi.Input<boolean>;
    /**
     * enable vm secure boot, only works when enable efi
     */
    enableSecureBoot?: pulumi.Input<boolean>;
    /**
     * enable vm TPM
     */
    enableTpm?: pulumi.Input<boolean>;
    /**
     * harvester image name
     */
    imageName?: pulumi.Input<string>;
    /**
     * enable vm isolatated emulator thread
     */
    isolateEmulatorThread?: pulumi.Input<boolean>;
    /**
     * harvester key pair name
     */
    keyPairName?: pulumi.Input<string>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    kind?: pulumi.Input<"HarvesterConfig">;
    /**
     * contents of kubeconfig file for harvester cluster, base64 is supported
     */
    kubeconfigContent?: pulumi.Input<string>;
    /**
     * size of memory for machine (in GiB)
     */
    memorySize?: pulumi.Input<string>;
    /**
     * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    metadata?: pulumi.Input<inputs.meta.v1.ObjectMeta>;
    /**
     * networkData content of cloud-init for machine, base64 is supported
     */
    networkData?: pulumi.Input<string>;
    /**
     * harvester network info
     */
    networkInfo?: pulumi.Input<string>;
    /**
     * harvester network model
     */
    networkModel?: pulumi.Input<string>;
    /**
     * harvester network name
     */
    networkName?: pulumi.Input<string>;
    /**
     * harvester network type
     */
    networkType?: pulumi.Input<string>;
    /**
     * size of reserved memory for machine (in MiB, integer value)
     */
    reservedMemorySize?: pulumi.Input<string>;
    /**
     * SSH password
     */
    sshPassword?: pulumi.Input<string>;
    /**
     * SSH port
     */
    sshPort?: pulumi.Input<string>;
    /**
     * SSH private key path 
     */
    sshPrivateKeyPath?: pulumi.Input<string>;
    /**
     * SSH username
     */
    sshUser?: pulumi.Input<string>;
    /**
     * userData content of cloud-init for machine, base64 is supported
     */
    userData?: pulumi.Input<string>;
    /**
     * harvester-vgpu-info
     */
    vgpuInfo?: pulumi.Input<string>;
    /**
     * harvester vm affinity, base64 is supported
     */
    vmAffinity?: pulumi.Input<string>;
    /**
     * harvester vm namespace
     */
    vmNamespace?: pulumi.Input<string>;
}
