// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { HarvesterConfigArgs } from "./harvesterConfig";
export type HarvesterConfig = import("./harvesterConfig").HarvesterConfig;
export const HarvesterConfig: typeof import("./harvesterConfig").HarvesterConfig = null as any;
utilities.lazyLoad(exports, ["HarvesterConfig"], () => require("./harvesterConfig"));

export { HarvesterConfigListArgs } from "./harvesterConfigList";
export type HarvesterConfigList = import("./harvesterConfigList").HarvesterConfigList;
export const HarvesterConfigList: typeof import("./harvesterConfigList").HarvesterConfigList = null as any;
utilities.lazyLoad(exports, ["HarvesterConfigList"], () => require("./harvesterConfigList"));

export { HarvesterConfigPatchArgs } from "./harvesterConfigPatch";
export type HarvesterConfigPatch = import("./harvesterConfigPatch").HarvesterConfigPatch;
export const HarvesterConfigPatch: typeof import("./harvesterConfigPatch").HarvesterConfigPatch = null as any;
utilities.lazyLoad(exports, ["HarvesterConfigPatch"], () => require("./harvesterConfigPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:rke-machine-config.cattle.io/v1:HarvesterConfig":
                return new HarvesterConfig(name, <any>undefined, { urn })
            case "kubernetes:rke-machine-config.cattle.io/v1:HarvesterConfigList":
                return new HarvesterConfigList(name, <any>undefined, { urn })
            case "kubernetes:rke-machine-config.cattle.io/v1:HarvesterConfigPatch":
                return new HarvesterConfigPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "rke-machine-config.cattle.io/v1", _module)
