opentelemetry-demo:
  default:
    # List of environment variables applied to all components
    env:
    # Javascript instrumentation (frontend and payment service), only on GCP, uses this env var
    # to set the namespace (and it will not be overriden by the k8sattributes processor in the collector
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_COLLECTOR_NAME
      value: opentelemetry-collector.opentelemetry-collector.svc.cluster.local
    - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      value: cumulative
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo
  components:
    # Is running standalone in a separate namespace, this gives a nicer demo
    loadgenerator:
      enabled: false
  jaeger:
    enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false
  opensearch:
    enabled: false
  opentelemetry-collector:
    enabled: false

