apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    meta.helm.sh/release-name: rke2-multus
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2025-05-15T10:03:54Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: network-attachment-definitions.k8s.cni.cncf.io
  resourceVersion: "601"
  uid: d6db51a6-20b5-429f-b653-cd7de0daabb5
spec:
  conversion:
    strategy: None
  group: k8s.cni.cncf.io
  names:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              config:
                type: string
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    plural: network-attachment-definitions
    shortNames:
    - net-attach-def
    singular: network-attachment-definition
  conditions:
  - lastTransitionTime: "2025-05-15T10:03:54Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-05-15T10:03:54Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
