// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ClusterArgs } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export const Cluster: typeof import("./cluster").Cluster = null as any;
utilities.lazyLoad(exports, ["Cluster"], () => require("./cluster"));

export { ClusterListArgs } from "./clusterList";
export type ClusterList = import("./clusterList").ClusterList;
export const ClusterList: typeof import("./clusterList").ClusterList = null as any;
utilities.lazyLoad(exports, ["ClusterList"], () => require("./clusterList"));

export { ClusterPatchArgs } from "./clusterPatch";
export type ClusterPatch = import("./clusterPatch").ClusterPatch;
export const ClusterPatch: typeof import("./clusterPatch").ClusterPatch = null as any;
utilities.lazyLoad(exports, ["ClusterPatch"], () => require("./clusterPatch"));

export { FeatureArgs } from "./feature";
export type Feature = import("./feature").Feature;
export const Feature: typeof import("./feature").Feature = null as any;
utilities.lazyLoad(exports, ["Feature"], () => require("./feature"));

export { FeatureListArgs } from "./featureList";
export type FeatureList = import("./featureList").FeatureList;
export const FeatureList: typeof import("./featureList").FeatureList = null as any;
utilities.lazyLoad(exports, ["FeatureList"], () => require("./featureList"));

export { FeaturePatchArgs } from "./featurePatch";
export type FeaturePatch = import("./featurePatch").FeaturePatch;
export const FeaturePatch: typeof import("./featurePatch").FeaturePatch = null as any;
utilities.lazyLoad(exports, ["FeaturePatch"], () => require("./featurePatch"));

export { SettingArgs } from "./setting";
export type Setting = import("./setting").Setting;
export const Setting: typeof import("./setting").Setting = null as any;
utilities.lazyLoad(exports, ["Setting"], () => require("./setting"));

export { SettingListArgs } from "./settingList";
export type SettingList = import("./settingList").SettingList;
export const SettingList: typeof import("./settingList").SettingList = null as any;
utilities.lazyLoad(exports, ["SettingList"], () => require("./settingList"));

export { SettingPatchArgs } from "./settingPatch";
export type SettingPatch = import("./settingPatch").SettingPatch;
export const SettingPatch: typeof import("./settingPatch").SettingPatch = null as any;
utilities.lazyLoad(exports, ["SettingPatch"], () => require("./settingPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:management.cattle.io/v3:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:ClusterList":
                return new ClusterList(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:ClusterPatch":
                return new ClusterPatch(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:Feature":
                return new Feature(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:FeatureList":
                return new FeatureList(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:FeaturePatch":
                return new FeaturePatch(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:Setting":
                return new Setting(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:SettingList":
                return new SettingList(name, <any>undefined, { urn })
            case "kubernetes:management.cattle.io/v3:SettingPatch":
                return new SettingPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "management.cattle.io/v3", _module)
